country_code = ""

[app]
debug = false
secret_key = ""
host = ""
port = 8015

[logging]
level = "INFO"
logfile_path = ""

[external_api]
auth_service_base_url = ""

[dodo_is_api_credentials]
client_id = ""
client_secret = ""

[database]
url = ""
